### ISSUE TITLE
Dataset on Hugging Face hub

### ISSUE THREAD

**Issue by loubnabnl** [yonsei-toc/CodeComple#2]
Hi thanks for contributing this dataset! I just wanted to let you know that it is now available on Hugging face hub in this [repo](https://huggingface.co/datasets/codeparrot/codecomplex), if you want to include the information in the readme, it can be loaded this way:
```python
from datasets import load_dataset

ds = load_dataset("codeparrot/codecomplex", split="train")
```

**Comment by narame7** [comment]
Hi! Thank you very much for your interest in our dataset :) It's great that our dataset can be simply loaded from huggingface library already!
